blueprint:
  name: Smart Rotary Switch (Event Mode) - Custom Click Actions
  description: >-
    Event-mode only automation for smart rotary switches using Zigbee2MQTT.
    Lets you choose what to do for single, double, and hold actions.

  domain: automation

  input:
    mqtt_topic:
      name: MQTT Topic
      description: The Zigbee2MQTT topic for your rotary switch (e.g., zigbee2mqtt/rotary_switch)
      selector:
        text:

    target_lights:
      name: Target Lights (optional)
      description: Lights to reference in your actions (use !input target_lights in actions)
      default: {}
      selector:
        target:
          entity:
            domain: light

    single_action:
      name: Single Press Action
      selector:
        action:
      default: []

    double_action:
      name: Double Press Action
      selector:
        action:
      default: []

    hold_action:
      name: Hold Action
      selector:
        action:
      default: []

mode: restart
max: 10
max_exceeded: silent

trigger:
  - platform: mqtt
    topic: !input mqtt_topic

action:
  - variables:
      payload: "{{ trigger.payload_json if trigger.payload_json is defined else {} }}"
      action: "{{ payload.action }}"
      lights: !input target_lights

  - choose:
      - conditions:
          - "{{ action == 'single' }}"
        sequence: !input single_action

      - conditions:
          - "{{ action == 'double' }}"
        sequence: !input double_action

      - conditions:
          - "{{ action in ['hold', 'long'] }}"
        sequence: !input hold_action
