blueprint:
  name: Smart Rotary Switch (Event Mode) - Custom Click Actions
  description: >-
    Event-mode only automation for smart rotary switches using Zigbee2MQTT.
    Lets you choose what to do for single, double, and hold actions, and dims/brightens on rotation.

  domain: automation

  input:
    mqtt_topic:
      name: MQTT Topic
      description: The Zigbee2MQTT topic for your rotary switch (e.g., zigbee2mqtt/rotary_switch)
      selector:
        text:

    target_lights:
      name: Target Lights (optional)
      description: Lights to reference in your actions (use !input target_lights in actions)
      default: {}
      selector:
        target:
          entity:
            domain: light

    single_action:
      name: Single Press Action
      selector:
        action:
      default: []

    double_action:
      name: Double Press Action
      selector:
        action:
      default: []

    hold_action:
      name: Hold Action
      selector:
        action:
      default: []

    rotate_step_size:
      name: Rotate Step Size (%)
      description: Brightness change per rotate event (1-50)
      default: 5
      selector:
        number:
          min: 1
          max: 50
          unit_of_measurement: "%"

    rotate_transition:
      name: Rotate Transition (s)
      description: Smoothing transition time applied to rotate changes
      default: 0.2
      selector:
        number:
          min: 0
          max: 5
          step: 0.05
          unit_of_measurement: "s"

mode: restart
max: 10
max_exceeded: silent

trigger:
  - platform: mqtt
    topic: !input mqtt_topic

action:
  - variables:
      payload: "{{ trigger.payload_json if trigger.payload_json is defined else {} }}"
      action: "{{ payload.action }}"
      lights: !input target_lights

      # Resolve selected entities from target (entities, areas, devices)
      _sel_entities: "{{ lights.entity_id | default([]) }}"
      _sel_areas: "{{ lights.area_id | default([]) }}"
      _sel_devices: "{{ lights.device_id | default([]) }}"
      _area_entities: "{{ _sel_areas | map('area_entities') | sum(start=[]) }}"
      _device_entities: "{{ _sel_devices | map('device_entities') | sum(start=[]) }}"
      all_light_entities: "{{ (_sel_entities + _area_entities + _device_entities) | unique | select('match','^light\\.') | list }}"

      # Configs
      _rot_transition: "{{ (rotate_transition | float) }}"

  - choose:
      - conditions:
          - "{{ action == 'single' }}"
        sequence: !input single_action

      - conditions:
          - "{{ action == 'double' }}"
        sequence: !input double_action

      - conditions:
          - "{{ action in ['hold', 'long'] }}"
        sequence: !input hold_action

      # Rotate Right -> jump to next level (1,64,128,191,255) for on lights
      - conditions:
          - "{{ action == 'rotate_right' }}"
        sequence:
          - variables:
              _on_lights: "{{ expand(all_light_entities) | selectattr('domain','eq','light') | selectattr('state','eq','on') | map(attribute='entity_id') | list }}"
              _ref: "{{ _on_lights[0] if _on_lights|length > 0 else none }}"
              _bri: "{{ state_attr(_ref, 'brightness') if _ref else 0 }}"
              _lvl_idx: >-
                {% set b = _bri | int(0) %}
                {% if b <= 1 %} 0
                {% elif b <= 64 %} 1
                {% elif b <= 128 %} 2
                {% elif b <= 191 %} 3
                {% else %} 4
                {% endif %}
              _next_idx: "{{ [4, _lvl_idx + 1] | min }}"
              _levels: "{{ [1,64,128,191,255] }}"
              _target_bri: "{{ _levels[_next_idx] }}"
          - condition: template
            value_template: "{{ _on_lights | length > 0 }}"
          - service: light.turn_on
            data:
              entity_id: "{{ _on_lights }}"
              brightness: "{{ _target_bri | int }}"
              transition: "{{ _rot_transition }}"

      # Rotate Left -> drop to previous level (1,64,128,191,255) for on lights
      - conditions:
          - "{{ action == 'rotate_left' }}"
        sequence:
          - variables:
              _on_lights: "{{ expand(all_light_entities) | selectattr('domain','eq','light') | selectattr('state','eq','on') | map(attribute='entity_id') | list }}"
              _ref: "{{ _on_lights[0] if _on_lights|length > 0 else none }}"
              _bri: "{{ state_attr(_ref, 'brightness') if _ref else 0 }}"
              _lvl_idx: >-
                {% set b = _bri | int(0) %}
                {% if b <= 1 %} 0
                {% elif b <= 64 %} 1
                {% elif b <= 128 %} 2
                {% elif b <= 191 %} 3
                {% else %} 4
                {% endif %}
              _prev_idx: "{{ [0, _lvl_idx - 1] | max }}"
              _levels: "{{ [1,64,128,191,255] }}"
              _target_bri: "{{ _levels[_prev_idx] }}"
          - condition: template
            value_template: "{{ _on_lights | length > 0 }}"
          - service: light.turn_on
            data:
              entity_id: "{{ _on_lights }}"
              brightness: "{{ _target_bri | int }}"
              transition: "{{ _rot_transition }}"
