blueprint:
  name: Zigbee2MQTT - Tuya 1-Button Scene Switch
  description: Automate your Tuya 1-Button Scene Switch via Zigbee2MQTT using MQTT device triggers.
  domain: automation
  input:
    switch:
      name: Tuya 1-Button Scene Switch
      description: Tuya 1-Button Scene Switch to use
      selector:
        device:
          integration: mqtt
    button_one_short_press:
      name: Single Press - Button
      description: Action to run on button single press
      default: []
      selector:
        action: {}
    button_one_double_press:
      name: Double Press - Button
      description: Action to run on button double press
      default: []
      selector:
        action: {}
    button_one_long_press:
      name: Long Press - Button
      description: Action to run on button long press
      default: []
      selector:
        action: {}
  source_url: https://gist.github.com/fr3nd/2d128a932708ad2238a9439fbc256514
mode: restart
max_exceeded: silent
trigger:
  - platform: device
    domain: mqtt
    device_id: !input "switch"
    type: action
    subtype: single
  - platform: device
    domain: mqtt
    device_id: !input "switch"
    type: action
    subtype: double
  - platform: device
    domain: mqtt
    device_id: !input "switch"
    type: action
    subtype: hold
action:
  - choose:
      - conditions:
          - "{{ trigger.type == 'action' and trigger.subtype == 'single' }}"
        sequence: !input "button_one_short_press"
      - conditions:
          - "{{ trigger.type == 'action' and trigger.subtype == 'double' }}"
        sequence: !input "button_one_double_press"
      - conditions:
          - "{{ trigger.type == 'action' and trigger.subtype == 'hold' }}"
        sequence: !input "button_one_long_press"
