blueprint:
  name: Zigbee2MQTT - Tuya 1-Button Scene Switch
  description: Automate your Tuya 1-Button Scene Switch via Zigbee2MQTT using MQTT topic subscriptions.
  domain: automation
  input:
    device_topic:
      name: Device Topic
      description: The zigbee2mqtt topic for your device (e.g., zigbee2mqtt/device_name)
      selector:
        text:
    button_one_short_press:
      name: Single Press - Button
      description: Action to run on button single press
      default: []
      selector:
        action: {}
    button_one_double_press:
      name: Double Press - Button
      description: Action to run on button double press
      default: []
      selector:
        action: {}
    button_one_long_press:
      name: Long Press - Button
      description: Action to run on button long press
      default: []
      selector:
        action: {}
mode: restart
max_exceeded: silent
trigger:
  - platform: mqtt
    topic: !input "device_topic"
action:
  - choose:
      - conditions:
          - "{{ trigger.payload_json.action == 'single' }}"
        sequence: !input "button_one_short_press"
      - conditions:
          - "{{ trigger.payload_json.action == 'double' }}"
        sequence: !input "button_one_double_press"
      - conditions:
          - "{{ trigger.payload_json.action == 'hold' }}"
        sequence: !input "button_one_long_press"
